default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: url_shortener_development

test:
  <<: *default
  database: url_shortener_test
